### PR TITLE
Create a separate staging environment

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Hei @leio10!

This PR is not meant to be merged as is, but just to open a discussion.

I run seeds on my development copy of census and I was suprised that I didn't get any test users (system0/system, and all those). The reason is that I need to set the SEED environment variable so that those actually get created. I thought that this environment variable name was a bit misleading, maybe `SEED_TEST_DATA` or something like that would be better. But then I thought that maybe the most flexible and safe solution is to actually create a separate `staging` environment, and only skip seeding test data in the production environment.

Thoughts?

### CODE REVIEW

**Comment by leio10** [comment]
Yes, I've already thought about it before. My aim is to have the staging environment with almost the same settings than production. IMHO we should have some kind of inheritance to perform only the minimum changes to get the staging env working properly.

Regarding the SEED variable, I've changed that recently to unify several variables we have had, and I used SEED because is the same name that Decidim uses. Anyway, I think that you are right in what you are saying: not production environments should seed data by default. But, I would use something like
```ruby
if !Rails.env.production? || ENV["SEED"]
  # do the seed
```

**Comment by deivid-rodriguez** [comment]
Yeah, staging should match production as much as possible but I still think it warrants its own environment so you can tweak things like the seed process without resorting to a weird environment variable.  But that's a separate discussion, not very important now :)

I'll close this and use the solution you're suggesting in a separate PR :+1:

**Comment by leio10** [comment]
@deivid-rodriguez isn't posible to create a inherited environment? I'm thinking in something like:

```ruby
# config/environment/staging.rb

require "production"

Rails.application.configure do
  # override production settings
end
```

**Comment by deivid-rodriguez** [comment]
Yeah, I guess that should work too :+1:. Do you want me to reopen a add that?

**Comment by deivid-rodriguez** [comment]
Actually I say let's leave it as it is now until we need an actual divergence for the staging configuration. At that point we can create a full blown separate staging environment and apply the solution you propose here. What do you think?

**Pull request closed without merging**
